" DO NOT EDIT THIS FILE
" Add your own customizations in /usr/share/vim_runtime/my_configs.vim

set runtimepath+=/usr/share/vim_runtime

source /usr/share/vim_runtime/vimrcs/basic.vim
source /usr/share/vim_runtime/vimrcs/filetypes.vim
source /usr/share/vim_runtime/vimrcs/plugins_config.vim
source /usr/share/vim_runtime/vimrcs/extended.vim
try
  source /usr/share/vim_runtime/my_configs.vim
catch
endtry